module.exports = {
    SET_CURRENT_CHAT: 'SET_CURRENT_CHAT',
    ADD_CHAT_NOTIFICATION: 'ADD_CHAT_NOTIFICATION',
    REMOVE_CHAT_NOTIFICATION: 'REMOVE_CHAT_NOTIFICATION',
    SET_HELP: 'SET_HELP',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_NAME_CHECK_TIMEOUT_INTERVAL: 'SET_NAME_CHECK_TIMEOUT_INTERVAL',
    CLEAR_NAME_CHECK_TIMEOUT_INTERVAL: 'CLEAR_NAME_CHECK_TIMEOUT_INTERVAL'
}
