module.exports = {
    SET_USERNAME: 'SET_USERNAME',
    SET_ROOM: 'SET_ROOM',
    RESET_LOCAL: 'RESET_LOCAL',
    ADD_MESSAGE: 'ADD_MESSAGE',
    SET_JOINING: 'SET_JOINING',
    SET_PLAYING_LOCAL: 'SET_PLAYING_LOCAL',
    SET_TANK_LOCAL: 'SET_TANK_LOCAL',
    SET_TANK_BOARD: 'SET_TANK_BOARD',
    SET_TURN_LOCAL: 'SET_TURN_LOCAL'
}