module.exports = {
    ADD_USER: 'ADD_USER',
    REMOVE_USER: 'REMOVE_USER',
    RESET_ONLINE: 'RESET_ONLINE',
    SET_PLAYING_ONLINE: 'SET_PLAYING_ONLINE',
    SET_TANK_ONLINE: 'SET_TANK_ONLINE',
    SET_TURN_ONLINE: 'SET_TURN_ONLINE',
    SET_PREVIOUS_NEXT_ONLINE: 'SET_PREVIOUS_NEXT_ONLINE',
    SET_FIRST_ONLINE: 'SET_FIRST_ONLINE',
    SET_READY_ONLINE: 'SET_READY_ONLINE',
    DECREMENT_ACTIONS_ONLINE: 'DECREMENT_ACTIONS_ONLINE',
    RESET_ACTIONS_ONLINE: 'RESET_ACTIONS_ONLINE',
    DECREMENT_HEALTH_ONLINE: 'DECREMENT_HEALTH_ONLINE',
    ADD_POINTS_ONLINE: 'ADD_POINTS_ONLINE'
}